---
- name: Install Apache
  ansible.builtin.yum:
    name: httpd
    state: present

- name: Copy FQDN-based index.html
  ansible.builtin.template:
    src: "{{ inventory_hostname }}.html.j2"
    dest: /var/www/html/index.html
    mode: '0444'
  notify: Restart Apache

- name: Ensure Apache is enabled
  ansible.builtin.service:
    name: httpd
    enabled: yes
    state: started

