---
- name: Create cloudadmins group
  group:
    name: cloudadmins
    state: present

- name: Create users
  user:
    name: "{{ item }}"
    groups: cloudadmins,wheel
    append: yes
    state: present
    shell: /bin/bash
  loop:
    - user100
    - user200
    - user300

- name: Generate SSH keys
  user:
    name: "{{ item }}"
    generate_ssh_key: yes
    ssh_key_file: ".ssh/id_rsa"
  loop:
    - user100
    - user200
    - user300

- name: Fetch private key for user100 to local machine
  fetch:
    src: "/home/user100/.ssh/id_rsa"
    dest: "./user100_private_keys/"
    flat: yes

